### ISSUE TITLE
Add task to retrieve latest deploy time

### ISSUE THREAD

**Issue by decentral1se** [aptivate/dye#106]
Is this already here? Whilst this should probably be viewable on some UI, it'd be better than nothing to have the `./tasks.py deploy ...` command create a small file which stamps when it was last run on the server side. This would be helpful for other members of the team to come along and check when the last release was (outside of the developer).

**Comment by lwm** [comment]
Ah, since we store all the versions in `/var/django/` I suppose it is just a matter of retrieving that. It would be nice to store a list off **all** deployments then. To see from the beginning.
