### ISSUE TITLE
Optimise when running huge mysql dumps

### ISSUE THREAD

**Issue by decentral1se** [aptivate/dye#115]
When doing a `restore_db`, sometimes you see:

> ERROR 2006 (HY000) at line 1493: MySQL server has gone away

The import gets cut off and it's done. That sucks.

Perhaps DYE can pass options to stop this happening: https://dba.stackexchange.com/questions/5292/mysql-server-has-gone-away-obstructing-import-of-large-dumps

**Comment by lwm** [comment]
This was solved with some `/etc/my.cnf` configuration, mainly:

```
[mysqld]
wait_timeout=900
max_allowed_packet=512M
```

We could probably warn about that somehow based on the size of the import.
