### ISSUE TITLE
Should be possible to select a Python in project_settings.py

### ISSUE THREAD

**Issue by qris** [aptivate/dye#59]
We will soon have python 2.7 available (as `/usr/bin/python2.7`) on CentOS 6 servers, where `/usr/bin/python` is python 2.6.

Applications needing Python 2.7 will need to bootstrap their virtualenv using it. We manually modified `bootstrap.py` in Washwatch, changing the shebang line to run Python 2.7. However this requires `/usr/bin/python2.7` to be available on all machines where Washwatch will ever be deployed (by fabric), which is not ideal.

I think it would be good to be able to specify a minimum Python version in project_settings.py, and then bootstrap tries to find one that meets the requirements by looking in various paths (starting with the system python in `/usr/bin/python`), and fails if it can't find one.

What do you think?

**Comment by foobacca** [comment]
We do now have a check in ve_mgr.py that the python in the virtualenv is the correct one, but that only runs after the virtualenv is built.  We should really flag the error before creating the virtualenv ...

**Comment by foobacca** [comment]
I think with the latest commit I've covered the use cases here.
